[project]
name = "PySpice"
version = "1.6"
description = "Simulate electronic circuit using Python and the Ngspice / Xyce simulators"
author = {name = "Fabrice Salvaire", email="pyspice@fabrice-salvaire.fr"}
license = "AGPL-3.0-or-later"
keywords = ["ngspice", "xyce", "spice", "berkeley", "electronic", "circuit", "simulation", "simulator"]
# cf. http://pypi.python.org/pypi?%3Aaction=list_classifiers
classifiers = [
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Education",
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.15",
]
readme = "README.md"
requires-python = ">=3.15"
dependencies = [
    "PyYAML>=5.3",
    "cffi>=1.14",
    "matplotlib>=3.2",
    "numpy>=1.18",
    "ply>=3.11",
    "scipy>=1.4",
    "requests>=2.23",
]


[project.urls]
Homepage = "https://pyspice.fabrice-salvaire.fr"
#  https://github.com/FabriceSalvaire/PySpice


[dependency-groups]
dev = [
    "rassumfrassum>=0.3.4",
    "ruff>=0.16.5",
    "ty>=0.0.75",
]


[tool.ruff]
# Exclude a variety of commonly ignored directories
# exclude = [...]

line-length = 100
indent-width = 4

target-version = "py315"


[tool.ruff.lint]
preview = true

# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
# select = ["E4", "E7", "E9", "F"]
select = [
# pycodestyle
"E",
# Pyflakes
"F",
# pyupgrade
"UP",
# flake8-bugbear
"B",
# flake8-simplify
"SIM",
# isort
"I",
]
ignore = [
"E302", # blank-lines-top-level
"E305", # blank-lines-after-function-or-class
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
# dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"


[tool.ruff.format]
quote-style = "preserve"   # else single | double
indent-style = "space"
# skip-magic-trailing-comma = false
# line-ending = "auto"

# reStructuredText code/literal blocks and doctests are all supported.
# This is currently disabled by default, but it is planned for this to be opt-out in the future.
# docstring-code-format = false
#
# Set the line length limit used when formatting code snippets in docstrings.
# This only has an effect when the `docstring-code-format` setting is enabled.
# docstring-code-line-length = "dynamic"
