[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
# requires = ["uv_build >= 0.12.5, <0.13.0"]
# build-backend = "uv_build"

[project]
name = "PySpice"
version = "1.6"

dependencies = [
  "PyYAML>=6.0.3",
  "cffi>=2.1.1",
  "colorama>=0.4.6",  # pyspice_post_installation.py
  "matplotlib>=3.11.1",
  "numpy>=2.5.2",
  "ply>=3.11",  # PySpice/Spice/Parser/Parser.py
  "requests>=2.34.2", # pyspice_post_installation.py
  "scipy>=1.18.1",
]

requires-python = ">=3.15"

author = {name = "Fabrice SALVAIRE", email="pyspice@fabrice-salvaire.fr"}
maintainer = {name = "Fabrice SALVAIRE", email="pyspice@fabrice-salvaire.fr"}
description = "Simulate electronic circuit using Python and the Ngspice / Xyce simulators"
readme = "README.md"
license = "AGPL-3.0-or-later"
license-files = ["LICENSE.md"]  # "agpl-3.0.md"
keywords = ["ngspice", "xyce", "spice", "berkeley", "electronic", "circuit", "simulation", "simulator"]
classifiers = [
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Education",
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.15",
]

[project.urls]
# cf. https://packaging.python.org/en/latest/specifications/well-known-project-urls/#well-known-labels
Homepage = "https://pyspice.fabrice-salvaire.fr"
Source = "https://github.com/FabriceSalvaire/PySpice"
# Download = ""
# Changelog = ""
# ReleaseNotes = ""
# Documentation = ""
# Issues = ""
# Funding = ""


[dependency-groups]
dev = [
  "hatchling>=1.32.0",
  "invoke>=3.0.3",
  "rassumfrassum>=0.3.4",
  "ruff>=0.16.5",
  "ty>=0.0.75",
  # beautifulsoup4
  #
  # PyGithub
  #
  # # Build documentation
  # sphinx
  # sphinxcontrib-getthecode
  # pyterate
  # pelican
]


[tool.hatch.build.targets.sdist]
# https://hatch.pypa.io/latest/config/build/#file-selection
only-include = ["PySpice"]
# include = [
# ]
# exclude = [
# ]

[tool.hatch.build.targets.wheel]
packages = ["PySpice"]

[tool.ruff]
# Exclude a variety of commonly ignored directories
# exclude = [...]

line-length = 140
indent-width = 4

target-version = "py315"


[tool.ruff.lint]
preview = true

# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
# select = ["E4", "E7", "E9", "F"]
select = [
# pycodestyle
"E",
# Pyflakes
"F",
# pyupgrade
"UP",
# flake8-bugbear
"B",
# flake8-simplify
"SIM",
# isort
"I",
]
ignore = [
  "E265", # no-space-after-block-comment
  "E302", # blank-lines-top-level
  "E305", # blank-lines-after-function-or-class
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
# dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"


[tool.ruff.format]
quote-style = "preserve"   # else single | double
indent-style = "space"
# skip-magic-trailing-comma = false
# line-ending = "auto"

# reStructuredText code/literal blocks and doctests are all supported.
# This is currently disabled by default, but it is planned for this to be opt-out in the future.
# docstring-code-format = false
#
# Set the line length limit used when formatting code snippets in docstrings.
# This only has an effect when the `docstring-code-format` setting is enabled.
# docstring-code-line-length = "dynamic"
