#! /usr/bin/env python3
# -*- Python -*-

####################################################################################################
#
# PySpice - A Spice Package for Python
# Copyright (C) 2014 Fabrice Salvaire
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
####################################################################################################

####################################################################################################

import glob
import os
import subprocess
import sys

####################################################################################################

examples_path = os.path.dirname(__file__)

for topic in os.listdir(examples_path):
    python_files = glob.glob(os.path.join(os.path.dirname(__file__), topic, '*.py'))
    for file_name in python_files:
        if file_name.islower():
            print('Run {}'.format(file_name))
            subprocess.call(('python', file_name))
            print('To continue press Enter')
            rc = sys.stdin.readline().strip()
