#! /bin/bash
mv .git .git-backup
git init
bzr fast-export --plain --git-branch=master | git fast-import
git remote add origin git@github.com:FabriceSalvaire/PySpice.git
git push origin master # --force
# End
