#! /bin/bash

####################################################################################################

input=$(realpath $1)
dst=$(realpath $2)

basename=${input%.m4}
basename=${basename##*/}

####################################################################################################

m4_path=$HOME/texmf/Circuit_macros
density=300
transparent=white

####################################################################################################

tmp_dir=$(mktemp -d)
echo $tmp_dir

cat > ${tmp_dir}/picture.tex <<EOF
\documentclass[11pt]{article}
\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize
\pagestyle{empty}
\begin{document}
EOF

m4 -I${m4_path} pgf.m4 libcct.m4 ${input} | dpic -g >> ${tmp_dir}/picture.tex
if [ $? -gt 0 ]; then
  echo Error
  pushd ${tmp_dir}
  rm picture*
  rmdir ${tmp_dir}
  exit 1
fi

cat >> ${tmp_dir}/picture.tex <<EOF
\end{document}
EOF

pushd ${tmp_dir}
# cat picture.tex
pdflatex -shell-escape picture.tex
cp picture-figure0.pdf ${dst}/${basename}.pdf
rm picture*
popd
rmdir ${tmp_dir} # more safe than a rm -rf

convert -density ${density} -transparent ${transparent} ${dst}/${basename}.pdf ${dst}/${basename}.png

####################################################################################################
#
# End
#
####################################################################################################
