#! /usr/bin/env python3

####################################################################################################
#
# Generate a PDF and PNG image for a circuit macros input
#
####################################################################################################

import argparse
import os

import PySpice.Doc.CircuitMacrosGenerator as CircuitMacrosGenerator

####################################################################################################

argument_parser = argparse.ArgumentParser(
    description='Generate a PDF and PNG image for a circuit macros input.')

argument_parser.add_argument('m4_path', metavar='M4_PATH',
                             help='m4 path')

argument_parser.add_argument('dst_path', metavar='DST_PATH',
                             help='destination path')

args = argument_parser.parse_args()

CircuitMacrosGenerator.generate(os.path.realpath(args.m4_path),
                                os.path.realpath(args.dst_path))
