#! /bin/bash

####################################################################################################
# 
# PySpice - A Spice package for Python
# Copyright (C) 2014 Salvaire Fabrice
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>. 
# 
####################################################################################################

# Clean the repository 

####################################################################################################

root_dir=`dirname $0`
root_dir=`dirname ${root_dir}`

rm -rf ${root_dir}/build
rm -rf ${root_dir}/dist
find ${root_dir} -name "*pyc" -exec rm {} \;
find ${root_dir} -name "*~" -exec rm {} \;
find ${root_dir} -name "*_flymake.py" -exec rm {} \;

####################################################################################################
#
# End
#
####################################################################################################
