#! /usr/bin/env python
# -*- Python -*-

####################################################################################################
# 
# PySpice - A Spice package for Python
# Copyright (C) Salvaire Fabrice 2014
# 
####################################################################################################

####################################################################################################

import argparse
import sys
    
####################################################################################################
#
# Options
#

argument_parser = argparse.ArgumentParser(description='Format a RST table')

argument_parser.add_argument('-s',
                             dest='column_separator',
                             default='|',
                             help='CSV column separator')

argument_parser.add_argument('-rst',
                             action='store_true', default=False,
                             help='input is rst else CSV')

args = argument_parser.parse_args()

####################################################################################################

if args.rst:
    column_separator = ' + '
else:
    column_separator = args.column_separator

####################################################################################################

column_widths = []
lines = []
for line in sys.stdin:

    line = line.strip()

    if args.rst:
        if line.startswith('+-'):
            continue
        if line.startswith('|'):
            line = line[1:]
        if line.endswith('|'):
            line = line[:-1]

    columns = [x for x in [x.strip() for x in line.split(column_separator)] if x]
    lines.append(columns)
    if len(columns) > len(column_widths):
        column_widths.extend([0]*(len(columns) - len(column_widths)))
    for i, text in enumerate(columns):
        column_widths[i] = max(column_widths[i], len(text))

####################################################################################################

hline = '+' + '+'.join(['-'*(width+2) for width in column_widths]) + '+'
line_format = '|' + '+'.join([' {:<' + str(width) + '} ' for width in column_widths]) + '|'
for line in lines:
    print hline
    if len(line) < len(column_widths):
        line.extend(['']*(len(column_widths) - len(line)))
    print line_format.format(*line)
print hline

####################################################################################################
# 
# End
# 
####################################################################################################
