#! /usr/bin/env python
# -*- Python -*-

####################################################################################################

import subprocess

from setup_data import read

####################################################################################################

with open('README.rst', 'w') as f:
    f.write(read('README.txt'))

# subprocess.call('python setup.py --long-description | rst2html > /dev/null', shell=True)
subprocess.call('python setup.py --long-description | rst2html > README.html', shell=True)

####################################################################################################
# 
# End
# 
####################################################################################################
