#! /usr/bin/env python3
# -*- Python -*-

####################################################################################################

import subprocess

from setup_data import long_description

####################################################################################################

with open('README.rst', 'w') as f:
    f.write(long_description)

subprocess.call(('rst2html', 'README.rst', 'README.html'))
