#! /usr/bin/perl
# -*- perl -*-

exit(1)if (@ARGV < 2);

my $pattern  = $ARGV[0];
my $filename = $ARGV[1];

# print "$pattern $filename";

open(INPUT, $filename);

while (<INPUT>)
{
  exit(0) if (/$pattern/);
}

exit(1);

# End
