#! /usr/bin/env python3

####################################################################################################

import os

from github import Github

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

####################################################################################################

with (open(os.path.expanduser('~/.github-token'))) as f:
    token = f.read()

github = Github(login_or_token=token)

repo = github.get_repo('FabriceSalvaire/PySpice')

# for stargazer in repo.get_stargazers_with_dates():
#     print('{} | {}'.format(stargazer.starred_at, stargazer.user.login))
#     # print('{} / {} : {}'.format(stargazer.user.login, stargazer.user.name, stargazer.starred_at))

datetimes = [stargazer.starred_at for stargazer in repo.get_stargazers_with_dates()]
dates = matplotlib.dates.date2num(datetimes)
print(dates)

counts = range(1, len(dates) +1)
plt.grid()
plt.plot_date(dates, counts, 'o-')
plt.show()
