#! /usr/bin/env python3

####################################################################################################

import os

from github import Github

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

####################################################################################################

token_path = os.path.expanduser('~/.github-token')
with open(token_path, 'r') as f:
    token = f.readline().strip()
# token = ''

github = Github(login_or_token=token)

repo = github.get_repo('FabriceSalvaire/PySpice')

# for stargazer in repo.get_stargazers_with_dates():
#     print('{} | {}'.format(stargazer.starred_at, stargazer.user.login))
#     # print('{} / {} : {}'.format(stargazer.user.login, stargazer.user.name, stargazer.starred_at))

datetimes = [stargazer.starred_at for stargazer in repo.get_stargazers_with_dates()]
dates = matplotlib.dates.date2num(datetimes)

counts = range(1, len(dates) +1)

figure = plt.figure(1, (20, 10))
axe = plt.subplot(111)

axe.grid()
axe.plot_date(dates, counts, 'o-')
axe.set_title('Star count over time')
axe.set_ylim(0, (counts[-1] // 10) * 10 + 10)
plt.savefig('doc/sphinx/source/_static/stargazer.png', bbox_inches='tight')
# plt.show()
